config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :faculty do
    get 'questions', on: :collection
    match 'new_question', on: :collection, via: [:get, :post]
    match 'edit_question/:question_id', as: :edit_question, action: :edit_question, on: :collection, via: [:get, :put]
  end
  resources :student do
    get 'attempt', on: :collection
    get 'results', on: :collection
    post ':attempt_id/process_attempt', on: :collection, action: :process_attempt, as: :process_attempt
  end

  authenticated :user, lambda { |u| u.type=="Faculty" } do
    root :to => 'faculty#index', :as => :faculty_root
  end

  authenticated :user, lambda { |u| u.type=="Student" } do
    root :to => 'student#index', :as => :student_root
  end

  root :to => 'application#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include QuickActions
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  audited
  belongs_to :student

  # json :answer_data, default: []
  # boolean :completed, default: false
  # float :score, default: 0.0
  # float :percentage, default: 0.0

  before_update :update_result
  def update_result
    @result = Result.find_or_create_by(student_id: self.student_id, faculty_id: self.student.faculty_id)
    questions = Question.where(id: self.answer_data.map{|ans_d| ans_d['que_id']})
    score = self.answer_data.inject(0){|score, ans_d| score+(questions.find{|ques| ques.id==ans_d['que_id']}.right_answer==ans_d['answer'] ? 1.0 : 0.0) rescue 0.0}
    self.score = score
    @result.score = score
    self.percentage = (score*100)/self.answer_data.count
    @result.percentage = (score*100)/self.answer_data.count
    @result.out_of = self.answer_data.count
    @result.save!
  end
end

app/models/concerns/quick_actions.rb
module QuickActions
  extend ActiveSupport::Concern

  def user?
    self.class.superclass.name == 'User'
  end
end

app/models/faculty.rb
class Faculty < User
  audited
  has_many :students, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy

  before_validation :fill_password, if: :new_record?
  def fill_password
    self.password = "Faculty@123"
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/log.rb
class Audited::Audit
	default_scope { where('user_type != ? AND user_id != ?', '', 0) }
  before_create :check
  def check
    self.auditable_type = self.auditable.type if self.auditable.user?
    self.user_type = self.user.type if self.user
    self.comment = "#{self.user_type}: #{self.user.name rescue ''}(ID: #{self.user_id}) #{(self.auditable.user? ? 'Signed In' : (self.action.capitalize+'d '+self.auditable_type+'(ID:'+self.auditable_id.to_s+')'))}"
  end
end
class Log < Audited::Audit
end

app/models/question.rb
class Question < ApplicationRecord
	audited
  belongs_to :faculty
	validates :question, :answer_a, :answer_b, :answer_c, :answer_d, :right_answer, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
	audited
  belongs_to :student
  belongs_to :faculty
end

app/models/student.rb
class Student < User
	audited
	belongs_to :faculty
  has_many :results, dependent: :destroy
  has_many :assignments, dependent: :destroy
	validates :faculty_id, presence: true, numericality: { only_integer:true, greater_than_or_equal_to:1 }

  before_validation :fill_password, if: :new_record?
  def fill_password
    self.password = "Student@123"
  end

  def name
    "#{first_name} #{last_name}"
  end

  def form_assignment
    assignment = self.assignments.new
    questions = self.faculty.questions.shuffle.first(10)
    if questions.present?
      assignment.answer_data = questions.map{|question| {que_id: question.id, answer: nil}}
      assignment.save!
      return questions, assignment, false
    else
      return [], nil, "Opps! No questions for assignment."
    end
  end
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :type, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  protect_from_forgery with: :exception
  
  include ApplicationHelper  
  before_action :set_initial_variables

  def index  	
  end
end

app/controllers/faculty_controller.rb
class FacultyController < ApplicationController
  before_action :kick_out_student
  def index
    @students = current_user.students.order('created_at').page(params[:page]).per(10)
  end

  def questions
    @question = current_user.questions.new
    @questions = current_user.questions.page(params[:page]).per(10)
  end

  def new_question
    if request.get?
      @question = current_user.questions.new
    elsif request.post?
      @question = current_user.questions.new(question_params)
      @question.save!
    end
  end

  def edit_question
    begin
      params.require(:question_id)
      if request.xhr?
        @question = current_user.questions.find_by_id(params[:question_id])
        @action_name = params[:action]
        if request.put?
          @question.update(question_params)
          @action_name = "new_question"
        end
      end
    rescue => e
      @error = true
      @msg = e.message
    end
  end

  private
  def question_params
    params.require(:question).permit(:question, :answer_a, :answer_b, :answer_c, :answer_d, :right_answer)
  end

  def kick_out_student
    redirect_to student_root_path if current_user.type=='Student'
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :redirect_out_faculty

  def index
    @assignments = current_user.assignments.order('created_at desc').page(params[:page]).per(10)
  end

  def attempt
    @questions, @assignment, @error = current_user.form_assignment
    # debugger
  end

  def results
    
  end

  def process_attempt
    begin
      assignment_asnwers = params.require(:assignment).require(:answer_data)
      @assignment = current_user.assignments.find_by_id(params[:attempt_id])
      answer_data = @assignment.answer_data
      assignment_asnwers.each do |que_id, answer|
        answer_data.find{|ans_d| ans_d['que_id'] == que_id.to_i}['answer'] = answer
      end
      @assignment.completed = true
      if @assignment.save!
        raise "Success: Saved!"
      else
        raise "Error: #{@assignment.errors.full_messages.join(' ')}"
      end
    rescue => e
      @error = e.message
    end
    render :attempt
  end

  private
  def redirect_out_faculty
    redirect_to faculty_root_path if current_user.type=='Faculty'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_initial_variables
		@action_set_name = "#{params[:controller]}-#{params[:action]}".parameterize
  end
end

app/helpers/faculty_helper.rb
module FacultyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/faculty/_question_form.html.erb
<%= form_for @question, url: {action: (@action_name || 'new_question'), question_id: que_id, params:{que_count: (@questions || []).count, indx: params[:indx]}}, method: ((request.xhr? && params[:action]=="edit_question") ? 'PUT' : 'POST'), remote: true do |f| %>
  <div class="modal-body">
    <div class="form-field">
      <%= f.label :question %><br />
      <%= f.text_area :question, autofocus: true, class: 'form-control' %>            
    </div>
    <div class="new_question_options">
      <div class="answers_a_b">
        <div class="form-field">
          <%= f.label :answer_a %><br />
          <%= f.text_field :answer_a, class: 'form-control' %>            
        </div>
        <div class="form-field">
          <%= f.label :answer_b %><br />
          <%= f.text_field :answer_b, class: 'form-control' %>            
        </div>
      </div>
      <div class="answers_c_d">
        <div class="form-field">
          <%= f.label :answer_c %><br />
          <%= f.text_field :answer_c, class: 'form-control' %>            
        </div>
        <div class="form-field">
          <%= f.label :answer_d %><br />
          <%= f.text_field :answer_d, class: 'form-control' %>            
        </div>
      </div>
    </div>
    <div class="form-field">
      <%= f.label :right_answer %><br />
      <%= f.select :right_answer, ([['Answer a','answer_a'],['Answer b','answer_b'],['Answer c','answer_c'],['Answer d','answer_d']]), {}, {:class => 'form-control'} %>            
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary cancelQuestion" data-dismiss="modal">Cancel</button>
    <%= f.submit ((request.xhr? && params[:action]=="edit_question") ? "Update" : "Create"), class: 'btn btn-primary' %>
  </div>
  <script>
    function resetQuestionForm(){
      $.get("<%=new_question_faculty_index_path(question_id: que_id, popup_type: params[:action])%>")
    }
  </script>
<% end %>

app/views/faculty/_question_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="facultyNewQuestion" tabindex="-1" role="dialog" aria-labelledby="facultyNewQuestionTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="facultyNewQuestionTitle">New Question</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render partial: 'question_form', locals: {que_id: nil} %>
    </div>
  </div>
</div>
<script>
  $('.modal#facultyNewQuestion').on('hidden.bs.modal', function(){
    resetQuestionForm()
  })
</script>

app/views/faculty/_question_tr.html.erb
<tr id="tr_question_<%=question.id%>" class="question_tr">
  <th scope="row"><%= indx.to_i+1 %></th>
  <td class="table-success"><%= question.question %></td>
  <td class="table-info"><%= question.answer_a %></td>
  <td class="table-primary"><%= question.answer_b %></td>
  <td class="table-info"><%= question.answer_c %></td>
  <td class="table-primary"><%= question.answer_d %></td>
  <td class="table-warning"><%= question.send(question.right_answer) %></td>
  <td class="table-danger"><%= link_to "<i class='fa fa-edit'></i>".html_safe, edit_question_faculty_index_path(question, {indx: indx}), remote: true %></td>
</tr>

app/views/faculty/edit_question.js.erb
<% if request.put? %>
	// $('form#edit_question_<%=params[:question_id]%>').replaceWith("<%= j(render partial: 'question_form', locals: {que_id: nil}) %>")
	$('tr#tr_question_<%=params[:question_id]%>').replaceWith("<%= j(render partial: 'question_tr', locals: {question: @question, indx: params[:indx]}) %>")
	$('.modal#facultyNewQuestion').modal('hide')
<% else %>
	$('form#new_question').replaceWith("<%= j(render partial: 'question_form', locals: {que_id: params[:question_id]}) %>")
	$('.modal#facultyNewQuestion').modal('show')
<% end %>

app/views/faculty/index.html.erb
<div class="container">
  <h1 class="pb-5 py-3">Students</h1>

  <div class="card card-data">
    <div class="students-table-box">
      <table class="table table-hover table-striped table-sm students-table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" class="table-success">First Name</th>
            <th scope="col" class="table-info">Last Name</th>
            <th scope="col" class="table-warning">Email</th>
            <th scope="col" class="table-primary">DOB</th>
            <th scope="col" class="table-danger">Score</th>
            <th scope="col" class="table-warning">Percentage</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td colspan="7" class="table-default"></td>
          </tr>
          <% if @students.present? %>
            <% @students.each_with_index do |student, indx| %>
              <tr>
                <th scope="row"><%= indx+1 %></th>
                <td class="table-success"><%= student.first_name %></td>
                <td class="table-info"><%= student.last_name %></td>
                <td class="table-warning"><%= student.email %></td>
                <td class="table-primary"><%= student.date_of_birth.inspect %></td>
                <%@result = Faculty.last.results.find_by_student_id(student.id)%>
                <td class="table-danger"><%= @result ? @result.score : 'N/A' %></td>
                <td class="table-warning"><%= @result ? @result.percentage : 'N/A' %></td>
              </tr>
            <% end %>
            <% if @students.total_pages>1 %>
              <tr>
                <td colspan="7" class="table-default"></td>
              </tr>
              <tr class="paginate_tr">
                <td colspan="7" class="table-active"><%= paginate @students %></td>
              </tr>
            <% end %>
          <% else %>
            <tr class="no_student_found">
              <td colspan="7" class="table-danger">No Student Assigned! Please contact to Admin.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/faculty/new_question.js.erb
<% if request.post? %>
  $('.modal#facultyNewQuestion').modal('hide')
  $('table.questions-table tbody tr.no_question_found').remove()
  if ($('tr.question_tr').length<10) {
    <%indx = (Question.count%10)%>
    $('tr.question_tr').last().after("<%= j(render partial: 'question_tr', locals: {question: @question, indx: (indx.zero? ? 9 : indx-1)}) %>")
  } else if ($('tr.question_tr').length==0) {
    $('table.questions-table tbody').prepend("<%= j(render partial: 'question_tr', locals: {question: @question, indx: (indx.zero? ? 9 : indx-1)}) %>")
  } else {
    window.location = window.location.pathname+('?page=<%=(Question.count/10)+1%>')
  }
  $('form#new_question')[0].reset()
  $('form#new_question').attr('action', "<%= new_question_faculty_index_path(que_count: (params[:que_count].to_i+1)) %>")
<% else %>
  <% if params[:popup_type]=='edit_question' %>
    $('form#edit_question_<%=params[:question_id]%>').replaceWith("<%= j(render partial: 'question_form', locals: {que_id: nil}) %>")
  <% else %>
    $('form#new_question')[0].reset()
  <% end %>
<% end %>

app/views/faculty/questions.html.erb
<div class="container">
  <div class="pb-5 py-3 faculty_question_head_box">
    <div class="faculty_question_heading"><h1>Questions</h1></div>
    <div class="faculty_question_new_btn">
      <button class="btn btn-primary btn-sm float-right"  data-toggle="modal" data-target="#facultyNewQuestion" id="questionModalButton">
        New Question
      </button>
    </div>
  </div>

  <div class="card card-data">
    <div class="questions-table-box">
      <table class="table table-hover table-striped table-sm questions-table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" class="table-success">Question</th>
            <th scope="col" class="table-info">Answer A</th>
            <th scope="col" class="table-primary">Answer B</th>
            <th scope="col" class="table-info">Answer C</th>
            <th scope="col" class="table-primary">Answer D</th>
            <th scope="col" class="table-warning">Right Answer</th>
            <th scope="col" class="table-danger"><i class="fa fa-edit"></i></th>
          </tr>
          <tr>
            <td colspan="8" class="table-default"></td>
          </tr>
        </thead>
        <tbody>
          <% if @questions.present? %>
            <% @questions.each_with_index do |question, indx| %>
              <%= render partial: 'question_tr', locals: {question: question, indx: indx} %>
            <% end %>
            <% if @questions.total_pages>1 %>
              <tr>
                <td colspan="8" class="table-default"></td>
              </tr>
              <tr class="paginate_tr">
                <td colspan="8" class="table-active"><%= paginate @questions %></td>
              </tr>
            <% end %>
          <% else %>
            <tr class="no_question_found">
              <td colspan="8" class="table-danger">No Questions Created!</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render partial: 'question_modal' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"><%= Rails.application.class.parent_name %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user.type=='Faculty' %>
        <li class="nav-item <%= @action_set_name=='faculty-index' ? 'active' : '' %>">
          <a class="nav-link" href="<%= root_path %>">Students</a>
        </li>
        <li class="nav-item  <%= @action_set_name=='faculty-questions' ? 'active' : '' %>">
          <a class="nav-link" href="<%= questions_faculty_index_path %>">Questions</a>
        </li>
      <% else %>
        <li class="nav-item <%= @action_set_name=='student-index' ? 'active' : '' %>">
          <a class="nav-link" href="<%= root_path %>">Assignments</a>
        </li>
        <li class="nav-item <%= @action_set_name=='student-attempt' ? 'active' : '' %>">
          <a class="nav-link" href="<%= attempt_student_index_path %>">Take Test</a>
        </li>
        <!-- <li class="nav-item<%#= @action_set_name=='student-results' ? 'active' : '' %>">
          <a class="nav-link" href="<%#= results_student_index_path %>">Results</a>
        </li> -->
      <% end %>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <%= link_to 'Logout', destroy_user_session_path, class: 'btn btn-danger', id: "user_logout_btn" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenInstitute</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script> -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @action_set_name %>">
    <% if current_user.present? %>
      <%= render partial: 'layouts/navbar' %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/student/attempt.html.erb
<div class="container">
  <center><span style="color: red;">*Do not reload untill complete otherwith you will loose assignment.</span></center>
  <div class="row justify-content-md-center">
    <% unless @error.present? %>
      <div class="questions-cards-box col-md-8">
        <%= form_tag process_attempt_student_index_path(@assignment), method: :post do %>
          <div class="question-box">
            <% @questions.each_with_index do |question, indx| %>
              <div class="pb-3 py-3">
                <div class="card card-data question-card">
                  <div class="question_text">
                    <h5><b>Question <%=indx+1%>: </b><%=question.question%></h5>
                  </div>
                  <div class="ansers_box card card-data ">
                    <div class="card card-data answer answer_a form-field"><b>Option A: </b><%=question.answer_a%></div>
                    <div class="card card-data answer answer_b form-field"><b>Option B: </b><%=question.answer_b%></div>
                    <div class="card card-data answer answer_c form-field"><b>Option C: </b><%=question.answer_c%></div>
                    <div class="card card-data answer answer_d form-field"><b>Option D: </b><%=question.answer_d%></div>
                    <div class="form-field">
                      <b>Select your answer: </b>
                      <%= select_tag "assignment[answer_data][#{question.id}]", options_for_select([['Select', nil],['Option A','answer_a'],['Option B','answer_b'],['Option C','answer_c'],['Option D','answer_d']]), {class: 'form-control answer'} %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <div class="submit_assignment">
            <%= submit_tag "Submit", class: 'btn btn-lg btn-success' %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div>
        <h3><%= @error %></h3>
        <h4>Go to <%= link_to 'Assignment Detail page', student_root_path %></h4>
      </div>
    <% end %>
  </div>
</div>

app/views/student/index.html.erb
<div class="container">
  <div class="pb-5 py-3 faculty_question_head_box">
    <div class="faculty_question_heading"><h1>Attemps Details</h1></div>
    <!-- <div class="faculty_question_new_btn">
      <button class="btn btn-primary btn-sm float-right"  data-toggle="modal" data-target="#facultyNewQuestion" id="questionModalButton">
        New Question
      </button>
    </div> -->
  </div>

  <div class="card card-data">
    <div class="questions-table-box">
      <table class="table table-hover table-striped table-sm questions-table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col" class="table-success">No.of Questions</th>
            <th scope="col" class="table-info">Score</th>
            <th scope="col" class="table-primary">Percentage</th>
            <th scope="col" class="table-warning">Date</th>
            <th scope="col" class="table-danger">Completed</th>
          </tr>
          <tr>
            <td colspan="8" class="table-default"></td>
          </tr>
        </thead>
        <tbody>
          <% if @assignments.present? %>
            <% @assignments.each_with_index do |assignment, indx| %>
              <%#= render partial: 'question_tr', locals: {question: question, indx: indx} %>
              <tr id="tr_assignment_<%=assignment.id%>" class="assignment_tr">
                <th scope="row"><%= indx.to_i+1 %></th>
                <td class="table-success"><%= assignment.answer_data.count %></td>
                <td class="table-info"><%= assignment.score %></td>
                <td class="table-primary"><%= assignment.percentage %>%</td>
                <td class="table-warning"><%= assignment.created_at.to_date.inspect %></td>
                <td class="table-danger"><%= (assignment.completed ? 'Completed' : 'Not Completed') %></td>
              </tr>
            <% end %>
            <% if @assignments.total_pages>1 %>
              <tr>
                <td colspan="8" class="table-default"></td>
              </tr>
              <tr class="paginate_tr">
                <td colspan="8" class="table-active"><%= paginate @assignments %></td>
              </tr>
            <% end %>
          <% else %>
            <tr class="no_question_found">
              <td colspan="8" class="table-danger">You have not attempted Test yet! Please go to 'Take Test'.</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>